ego_relative_progress_to_goal_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.ego_relative_progress_to_goal.EgoRelativeProgressToGoalStatistics
  _convert_: 'all'
  name: 'ego_relative_progress_to_goal'
  category: 'Planning'
  min_relative_progress_rate: 0.5
