ego_progress_to_goal_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.ego_progress_to_goal.EgoProgressToGoalStatistics
  _convert_: 'all'
  name: 'ego_progress_to_goal'
  category: 'Planning'
  score_distance_threshold: 5.0
