kinematic_agent_augmentation:
  _target_: nuplan.planning.training.data_augmentation.kinematic_agent_augmentation.KinematicAgentAugmentor
  _convert_: 'all'

  augment_prob: 0.5  # probability of applying data augmentation for training
  mean: [1.0, 0.0, 0.0]  # the mean vector of the Gaussian noise on [x, y, heading]
  std: [1.0, 1.0, 0.5]  # the std vector of the Gaussian noise on [x, y, heading]
  trajectory_length: 12  # the augmentation trajectory length
  dt: 0.5  # the time interval between two consecutive points of the trajectory
