ego_at_fault_collisions_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.ego_at_fault_collisions.EgoAtFaultCollisionStatistics
  _convert_: 'all'
  name: 'ego_at_fault_collisions_statistics'
  category: 'Dynamics'

  max_violation_threshold: 0

  required_metrics:
    # Parameter: base metric name and other high level metrics used in this metric
    ego_lane_change_metric: ego_lane_change_statistics
