ego_safety_performance_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.ego_safety_performance.EgoSafetyStatistics
  _convert_: 'all'
  name: 'ego_safety_performance_statistics'
  category: 'Planning'

  required_metrics:
    # Parameter: base metric name and other high level metrics used in this metric
    time_to_collision_metric: time_to_collision_statistics
    drivable_area_violation_metric: drivable_area_violation_statistics
    ego_at_fault_collisions_metric: ego_at_fault_collisions_statistics
    ego_min_distance_to_lead_agent_metric: ego_min_distance_to_lead_agent_statistics
