speed_limit_violation_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.speed_limit_violation.SpeedLimitViolationStatistics
  _convert_: 'all'
  name: 'speed_limit_violation_statistics'
  category: 'Violations'
  max_violation_threshold: 1.0
  max_overspeed_value_threshold: 2.23

  required_metrics:
    # Parameter: base metric name and other high level metrics used in this metric
    drivable_area_violation_metric: drivable_area_violation_statistics
