time_to_collision_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.time_to_collision.TimeToCollisionStatistics
  _convert_: 'all'
  name: 'time_to_collision'
  category: 'Planning'

  time_step_size: 0.1
  time_horizon: 5.0
  least_min_ttc: 0.95

  required_metrics:
    # Parameter: base metric name and other high level metrics used in this metric
    ego_lane_change_metric: ego_lane_change_statistics
    ego_at_fault_collisions_metric: ego_at_fault_collisions_statistics
