hydra:
  run:
    dir: .
  output_subdir: null                                           # Store hydra's config breakdown here for debugging
  searchpath:                                                   # Only <exp_dir> in these paths are discoverable
    - pkg://nuplan.planning.script.config.common
    - pkg://nuplan.planning.script.experiments                  # Put experiments configs in script/experiments/<exp_dir>

defaults:
  # Hyperparameters need to be specified
  - metric_aggregator:
      - weighted_average_metric_aggregator

  - override hydra/job_logging: none                            # Disable hydra's logging
  - override hydra/hydra_logging: none                          # Disable hydra's logging

output_dir: ???                                                 # Main path for the existing simulation
date_format: '%Y.%m.%d.%H.%M.%S'                                # Date format
metric_folder_name: 'metrics'                                   # Metric folder name
